### ISSUE TITLE
Couldnt get field 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by copolycube** [wacken89/hetzner-load-balancer-prometheus-exporter#6]
Hello, 

I started your exporter with docker-compose:

```
  hetzner-load-balancer-prometheus-exporter:
    image: wacken/hetzner-load-balancer-prometheus-exporter:latest
    container_name: hetzner-lb
    expose:
            - 8000
    environment:
            - LOAD_BALANCER_IDS="<id redacted>,<id redacted>"
            - ACCESS_TOKEN="${HETZNER_API_TOKEN_READ}"
```
but it shows the following logs, I'm not sure if it's an "expected" message ?

```
hetzner-lb  | 2022-06-30T16:11:30.498488714Z Hetzner Load Balancer Exporter is starting ...
hetzner-lb  | 2022-06-30T16:11:30.498507667Z Getting Info from Hetzner ...
hetzner-lb  | 2022-06-30T16:11:30.498510184Z
hetzner-lb  | 2022-06-30T16:11:30.498511842Z Found Load Balancers
hetzner-lb  | 2022-06-30T16:11:30.536478067Z Couldnt get field 'NoneType' object is not subscriptable
```

Thanks in advance for your help !

**Comment by wacken89** [comment]
Hello, 
This problem appeared because of docker-compose syntax.
You need to set variables without quotes

https://docs.docker.com/compose/compose-file/compose-file-v3/#environment

```yaml
version: "3.9"
services:
  hetzner-load-balancer-prometheus-exporter:
    image: wacken/hetzner-load-balancer-prometheus-exporter:latest
    container_name: hetzner-lb
    expose:
      - 8000
    environment:
      - LOAD_BALANCER_IDS=531796,531794
      - ACCESS_TOKEN=${HETZNER_API_TOKEN_READ}
```

or 

```yaml
version: "3.9"
services:
  hetzner-load-balancer-prometheus-exporter:
    image: wacken/hetzner-load-balancer-prometheus-exporter:latest
    container_name: hetzner-lb
    expose:
      - 8000
    environment:
      LOAD_BALANCER_IDS: "531796,531794"
      ACCESS_TOKEN: "${HETZNER_API_TOKEN_READ}"
```
